### ISSUE TITLE
Question: `fourty` vs `forty`

### ISSUE THREAD

**Issue by tagliala** [floraison/fugit#107]
Hello,

https://github.com/floraison/fugit/blob/128e2ed642b799ec9d2acb139bd58a5e7633ce01/lib/fugit/nat.rb#L57

https://github.com/floraison/fugit/blob/128e2ed642b799ec9d2acb139bd58a5e7633ce01/spec/nat_spec.rb#L173

`codespell` identifies fourty as a typo, but since this is production code I didn't fix it and also it looks somehow legit because there are several occurrences of forty across many repositories: https://github.com/search?q=%22fourty+fifty%22&type=code

I'm not an expert of `cron`, so I'm not sure if this is a "spec" typo (like "referer" without the double r in HTML) left there for historical reasons.

Of course fixing this issue would be a breaking change, so I guess that should be deprecated and workarounded manually and probably it's not worth 

Refs:
- https://www.grammarly.com/blog/forty-fourty/

**Comment by jmettraux** [comment]
Hello, thanks for pointing that out. I will fix that by myself.

**Comment by jmettraux** [comment]
Thanks again.
