### ISSUE TITLE
parse_nat with weekday ranges doesn't parse correctly

### ISSUE THREAD

**Issue by shaicoleman** [floraison/fugit#27]
```
# Parses correctly with days specified individually
puts Fugit.parse_nat('every Fri,Sat,Sun at 18:00 UTC').weekdays.inspect
=> [[0], [5], [6]]

# Parses incorrectly with day ranges spanning the end of week
puts Fugit.parse_nat('every Fri-Sun at 18:00 UTC').weekdays.inspect
=> [[0], [1], [2], [3], [4], [5]]
```

**Comment by jmettraux** [comment]
@shaicoleman would it actually hurt you to say thanks for #24 and #25 ?

**Comment by shaicoleman** [comment]
No, it wouldn't. Thanks for everything, your work is truly appreciated.

**Comment by jmettraux** [comment]
You're welcome, thanks for the great feedback!

**Comment by jmettraux** [comment]
I have to fix that as well for cron`"0 19 * 11-3 0"` and `"0 19 * nov-mar 0"`.

**Comment by jmettraux** [comment]
Closing, I think I got it covered, I also had a look at the other possible ranges and added specs for them, and fixed the ones that were broken.
