### ISSUE TITLE
[Documentation] Regex for crontab notation

### ISSUE THREAD

**Issue by christianfl** [floraison/fugit#32]
Hi,

I'm working on a frontend which lets the user input a crontime to generate a cronjob for sidekiq-cron in the backend.

I'm validating the string backend-wise with your validate method but do you maybe have a regex for doing the validation in the frontend, too? A good documentation which cron string is allowed would also work, of course.

Typical cron regexes didn't work because of your optional 6 digit syntax and so on..

Thank you in advance!

**Comment by jmettraux** [comment]
Hello,

I don't have a regex, sorry.

I don't really have a documentation, but there's the [cron parser](https://github.com/floraison/fugit/blob/b6dea6a4ff1e9f43f45ee80d6acb0a825b507f71/lib/fugit/cron.rb#L592-L688) itself. It's using [raabro](https://github.com/floraison/raabro) like the other parsers in fugit.

I hope this will help you.

I am closing the issue but not the conversation. Best regards!
