### ISSUE TITLE
Fugit::Cron previous_time method bug

### ISSUE THREAD

**Issue by zhangyonguu** [floraison/fugit#33]
Hi, there:

  I was in +8 timezone, I exec the following statement in rails console:
 ```Fugit::Cron.parse('0 16 30 9 *').previous_time.to_local_time```

and I got the following error:
`RuntimeError: too many loops for "0 16 30 9 *" #previous_time, breaking`

Also, the same error occurred when I exec:
 ```Fugit::Cron.parse('0 16 31 10 *').previous_time.to_local_time```

I guess that when the cron is across the month, this error occurred. So boundary conditions need  
to be fully considered

**Comment by jmettraux** [comment]
@zhangyonguu Hello, could you please update your issue to indicate what version of fugit and what version of Ruby you are using? Thanks in advance.

**Comment by jmettraux** [comment]
@zhangyonguu Oh, one more thing. Could you please give me the output of the three following commands on your system and in Rails project?

```
uname -a                                                                                     
ruby -v                                                                          
bundle exec ruby -r et-orbi -e "EtOrbi._make_info"  
```

Thanks in advance!

**Comment by zhangyonguu** [comment]
```

**Comment by jmettraux** [comment]
> @jmettraux, my fugit version is 1.1.8 and my Ruby version is 2.4.1

Ah, then could you please upgrade your fugit version to the latest which is 1.3.3 (https://rubygems.org/gems/fugit/versions/1.3.3). It should fix the issue.

According to the https://github.com/floraison/fugit/blob/master/CHANGELOG.md it should be fixed at 1.1.9.

Please tell me how it turns out. Thanks in advance.

**Comment by zhangyonguu** [comment]
@jmettraux , yes, it works! Thank you!

**Comment by jmettraux** [comment]
You're welcome. Have a good evening!
