### ISSUE TITLE
Natural cron "every 15th of the month"

### ISSUE THREAD

**Issue by DannyBen** [floraison/fugit#38]
## Issue description

Trying to convert natural language to a cron expression that happens every specific day of the month.

Looking at the specs, I see that it was intended, but currently not working?

https://github.com/floraison/fugit/blob/7f4d5296e3e55e6c9853f14457af79d4b3e3a845/spec/nat_spec.rb#L48

Is it planned?

I don't even mind if it will be a little less natural language, like:

- `every month on day 2 at 10:00`
- `every month on days 1,15 at 10:00    # twice a month 1st and 15th`

if that makes it easier to implement.

## How to reproduce

```ruby
require 'fugit'
p Fugit::Nat.parse('Every 2nd of the month at 10:00')   #=> nil
```

**Comment by jmettraux** [comment]
I will implement that. Thanks.

**Comment by jmettraux** [comment]
@DannyBen Hello, I included your demand into the rework I did for the nat parser. Please tell me if it covers your need and I'll release then. If there are further cases that you'd need, please tell me. Thanks again.

**Comment by DannyBen** [comment]
Thanks a lot @jmettraux, for being open to it and for the quick update.

I tested the new sentences as defined in the specs against master and they work beautifully.

**Comment by DannyBen** [comment]
By the way - this release also fixes a bug.

With the current live release, this expression returns an invalid cron instead of `nil`:

```
Fugit::Nat.parse('Every month on day 6 at 10:00')
```

**Comment by jmettraux** [comment]
OK, great, I'll release in a few hours then. If you spot anything, please tell me.
