### ISSUE TITLE
undefined method `inject' for nil:NilClass

### ISSUE THREAD

**Issue by rafarosa92** [floraison/fugit#39]
## Issue description
undefined method `inject' for nil:NilClass

## How to reproduce

```ruby
c = Fugit::Cron.parse('0 0 * *  sun')
Traceback (most recent call last):
        2: from (irb):10
        1: from (irb):11:in `rescue in irb_binding'
NoMethodError (undefined method `inject' for nil:NilClass)
```

**Comment by jmettraux** [comment]
Good day @rafarosa92 

```ruby
require 'fugit'

c = Fugit::Cron.parse('0 0 * *  sun')

p c
p c.next_time.to_s
```
outputs
```
#<Fugit::Cron:0x0000044006aaa4c0 @original="0 0 * *  sun", @cron_s=nil, @seconds=[0], @minutes=[0], @hours=[0], @monthdays=nil, @months=nil, @weekdays=[[0]],
@zone=nil, @timezone=nil>
"2020-06-07 00:00:00 +0900"
```

```
$ uname -a
OpenBSD terebi 6.7 GENERIC.MP#1 amd64

$ ruby --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-openbsd6.6]

$ bundle list
Gems included by the bundle:
  * bundler (1.17.2)
  * chronic (0.10.2)
  * concurrent-ruby (1.1.6)
  * diff-lcs (1.3)
  * et-orbi (1.2.4)
  * fugit (1.3.6)
  * raabro (1.3.1)
  * rspec (3.9.0)
  * rspec-core (3.9.1)
  * rspec-expectations (3.9.1)
  * rspec-mocks (3.9.1)
  * rspec-support (3.9.2)
  * tzinfo (2.0.2)
```

So it works for me.

If you want me not to close this issue, you have to provide me a way to reproduce the problem.

Could you please indicate what OS you are using, what Ruby version you are using, and what fugit version you are using. Those things are requested by the issue template, but are missing from your issue report.

Thanks in advance.

**Comment by rafarosa92** [comment]
$ uname - a

Linux pop-os 5.3.0-7648-generic #41~1586789791~19.10~9593806-Ubuntu SMP Mon Apr 13 17:50:40 UTC  x86_64 x86_64 x86_64 GNU/Linux

$ruby --version
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

$bundle list
 
Gems included by the bundle:
  * actioncable (6.0.3.1)
  * actionmailbox (6.0.3.1)
  * actionmailer (6.0.3.1)
  * actionpack (6.0.3.1)
  * actiontext (6.0.3.1)
  * actionview (6.0.3.1)
  * activejob (6.0.3.1)
  * activemodel (6.0.3.1)
  * activerecord (6.0.3.1)
  * activestorage (6.0.3.1)
  * activesupport (6.0.3.1)
  * airbrussh (1.4.0)
  * bcrypt (3.1.13)
  * bootsnap (1.4.6)
  * builder (3.2.4)
  * byebug (11.1.3)
  * capistrano (3.14.0)
  * capistrano-bundler (1.6.0)
  * capistrano-passenger (0.2.0)
  * capistrano-rails (1.5.0)
  * capistrano-rbenv (2.1.6)
  * capistrano-sidekiq (1.0.2)
  * concurrent-ruby (1.1.6)
  * connection_pool (2.2.2)
  * crass (1.0.6)
  * devise (4.7.1)
  * devise-jwt (0.6.0)
  * domain_name (0.5.20190701)
  * dry-auto_inject (0.7.0)
  * dry-configurable (0.9.0)
  * dry-container (0.7.2)
  * dry-core (0.4.9)
  * e2mmap (0.1.0)
  * erubi (1.9.0)
  * et-orbi (1.2.4)
  * ffi (1.12.2)
  * figaro (1.2.0)
  * fugit (1.3.5)
  * globalid (0.4.2)
  * http-accept (1.7.0)
  * http-cookie (1.0.3)
  * i18n (1.8.2)
  * jwt (2.2.1)
  * listen (3.1.5)
  * loofah (2.5.0)
  * mail (2.7.1)
  * marcel (0.3.3)
  * mechanize (2.7.6)
  * method_source (1.0.0)
  * mime-types (3.3.1)
  * mime-types-data (3.2020.0512)
  * mimemagic (0.3.5)
  * mini_mime (1.0.2)
  * mini_portile2 (2.4.0)
  * minitest (5.14.1)
  * msgpack (1.3.3)
  * mysql2 (0.5.3)
  * net-http-digest_auth (1.4.1)
  * net-http-persistent (4.0.0)
  * net-scp (3.0.0)
  * net-ssh (6.0.2)
  * netrc (0.11.0)
  * nice_hash (1.16.3)
  * nio4r (2.5.2)
  * nokogiri (1.10.9)
  * ntlm-http (0.1.1)
  * orm_adapter (0.5.0)
  * puma (4.3.5)
  * raabro (1.3.1)
  * rack (2.2.2)
  * rack-cors (1.1.1)
  * rack-protection (2.0.8.1)
  * rack-test (1.1.0)
  * rails (6.0.3.1)
  * rails-dom-testing (2.0.3)
  * rails-html-sanitizer (1.3.0)
  * railties (6.0.3.1)
  * rake (13.0.1)
  * rb-fsevent (0.10.4)
  * rb-inotify (0.10.1)
  * redis (4.1.4)
  * regexp_parser (1.7.0)
  * responders (3.0.0)
  * rest-client (2.1.0)
  * ruby_dep (1.5.0)
  * rufus-scheduler (3.6.0)
  * sidekiq (6.0.7)
  * sidekiq-scheduler (3.0.1)
  * spring (2.1.0)
  * spring-watcher-listen (2.0.1)
  * sprockets (4.0.0)
  * sprockets-rails (3.2.1)
  * sshkit (1.21.0)
  * string_pattern (2.2.2)
  * thor (1.0.1)
  * thread_safe (0.3.6)
  * thwait (0.1.0)
  * tilt (2.0.10)
  * tzinfo (1.2.7)
  * unf (0.1.4)
  * unf_ext (0.0.7.7)
  * warden (1.2.8)
  * warden-jwt_auth (0.4.2)
  * webrobots (0.1.2)
  * websocket-driver (0.7.2)
  * websocket-extensions (0.1.4)
  * zeitwerk (2.3.0)


I´ll test on a docker with your settings...

**Comment by jmettraux** [comment]
Just tested on the same system but with fugit 1.3.5 as you do, and I can't see your error. It works as well.

**Comment by jmettraux** [comment]
@rafarosa92 Is the error backtrace in your initial report complete? It seems to obfuscate where the `NullMethodError` is actually occurring.

**Comment by jmettraux** [comment]
Just test on the same system with fugit 1.3.5 and `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-openbsd6.7]` (close enough to yours). Still successful. Tried both with my program and with irb as you do.

I'm not using Docker, I'm using a plain Ruby "project" with its .ruby-version and its Gemfile, it's at https://gist.github.com/jmettraux/f657b8b17a05de95ba55d5d7345b9e36

I have to go to bed now. Let's hope you can pinpoint the problem. Please provide a backtrace pointing at fugit or a way for me to reproduce the issue (and then fix it).

Best regards.

**Comment by rafarosa92** [comment]
Apparently the error is only within my project, because when I do the test by irb the methods work normally. I'll see what can be, we can close this topic.

Thanks for help!!

**Comment by jmettraux** [comment]
You're welcome. If you spot anything else related to fugit, please open a new issue.
