### ISSUE TITLE
cron time + DST trouble

### ISSUE THREAD

**Issue by grosser** [floraison/fugit#48]
I'm using `Fugit.parse('55 6 * * 2#1 America/Los_Angeles')` for a monthly alert.
This has been alerting fine at 6:55 all the time, but 2020-12-01 it alerted 1 hour early (5:55).
Last time it alerted `Nov 3 at 6:55 AM` which was in DST already, so I'd have expected that to fail and not the December one, but there is a chance it was scheduled before DST kicked in.
I reproduced the issue using `Timecop.travel('2020-11-30')` and `Fugit.parse('55 6 * * 2#1 America/Los_Angeles').next_time.to_debug_s` and it looks like the timezone is wrong:

```
Timecop.travel('2020-11-30')
# => 2020-11-30 00:00:00 -0800
Fugit.parse('55 6 * * 2#1 America/Los_Angeles').next_time.to_s
# => "2020-12-01 07:55:00 -0700" <-- wrong ?
Time.now
# => 2020-11-30 00:09:15 -0800
```

**Comment by jmettraux** [comment]
Hello,

quick question, what version of fugit are you using?

**Comment by grosser** [comment]
1.3.3
.... update all my gems, but results were the same, will deploy that and see if the alert comes early again

**Comment by jmettraux** [comment]
Thanks.

1.3.9 has a change in the way it deals with DST transition, hence my question. I will test on 1.4.1.

**Comment by grosser** [comment]
sounds like the bug I saw, I'll report back in a month if it reproduces :)

**Comment by jmettraux** [comment]
Could you please give me the output of

```
uname -a
bundle exec ruby -v
bundle exec ruby -e "p [ :env_tz, ENV['TZ'] ]"
bundle exec ruby -r et-orbi -e "EtOrbi._make_info"
bundle exec ruby -r fugit -e "p Fugit::VERSION"
```

on your system?

Thanks in advance.

**Comment by grosser** [comment]
don't work on this, good chance it's done ... will report back if it's not :)
