### ISSUE TITLE
Don't double cron matches when getting out of DST

### ISSUE THREAD

**Issue by jakemack** [floraison/fugit#6]
Fugit::Cron does not handle the edge cases of daylight saving time.

`Fugit::Cron.new("0 0 * * * America/New_York").brute_frequency` shows 365 occurrences, which makes sense at one per day for a year. However, `Fugit::Cron.new("1 1 * * * America/New_York").brute_frequency` shows 366 occurrences (since 1:01 a.m. occurs twice when moving the clock backwards) and `Fugit::Cron.new("1 2 * * * America/New_York").brute_frequency` shows 364 occurrences (since 2:01 a.m. is skipped when moving the clock forward).

As I quickly researched around the internet, I see that this support is dependent on the version of cron used but I think this is a good feature to have. What are your thoughts on adding in this support?

**Comment by jmettraux** [comment]
Hello,

thanks for the suggestion. `#brute_frequency` results are just indicative, none of the downstream libraries use it. As long as DST is respected by `#next_time`, I do not want to invest time in changing that. As it is, it is good for me.

Best regards.

**Comment by jakemack** [comment]
I can show the same issue using `#next_time` as well. Given a cron that should run every day at 1:59 a.m., `#next_time` will return two times on the same day, depending on when it is measuring from.

```ruby
2.3.3 :120 > cron = Fugit::Cron.new("59 1 * * * America/New_York")
 => #<Fugit::Cron:0x0000000a4010a0 @original="59 1 * * * America/New_York", @cron_s=nil, @seconds=[0], @minutes=[59], @hours=[1], @monthdays=nil, @months=nil, @weekdays=nil, @zone="America/New_York", @timezone=#<TZInfo::DataTimezone: America/New_York>>
2.3.3 :121 > t = EtOrbi.make_time("2018-11-04 01:55:00 -0400")
 => #<EtOrbi::EoTime:0x0000000a4e4da0 @seconds=1541310900.0, @zone=#<TZInfo::DataTimezone: -0400>, @time=nil>
2.3.3 :122 > cron.next_time(t).to_t
 => 2018-11-04 01:59:00 -0400
2.3.3 :123 > t = EtOrbi.make_time("2018-11-04 01:59:00 -0400")
 => #<EtOrbi::EoTime:0x0000000a811050 @seconds=1541311140.0, @zone=#<TZInfo::DataTimezone: -0400>, @time=nil>
2.3.3 :124 > cron.next_time(t).to_t
 => 2018-11-04 01:59:00 -0500
```

As you can see, the second time is only one hour after the first, both on 2018-11-04.

**Comment by jmettraux** [comment]
OK, I will investigate that. Give me some time.

**Comment by jakemack** [comment]
Thanks! If I get some free time to look into it further before you get to it, I'll leave any new findings here.

**Comment by jmettraux** [comment]
Hello @jakemack,

please have a look at the change I made. Do tell me if it solves the issue. If yes, I will release fugit 1.1.4 with it. If not, we will iterate further.

Best regards.

**Comment by jakemack** [comment]
Thanks for the quick turnaround! I should have time to test today, I'll report back my results once I do

**Comment by jakemack** [comment]
I ran out of time yesterday but got to it this morning. Everything works as my tests expected! Thanks so much for the speedy solution. I had been putting off upgrading to rufus-scheduler 3 for months and then was sad when I ran into this issue. Now I'm very happy to see the finish line for the upgrade approaching! Feel free to close the issue when you see fit.

**Comment by jmettraux** [comment]
Thanks a lot, I'll release today then.

> I had been putting off upgrading to rufus-scheduler 3 for months 

I am curious, from what are you upgrading from?

**Comment by jakemack** [comment]
rufus-scheduler (2.0.24)

**Comment by jmettraux** [comment]
Thanks again!

**Comment by jmettraux** [comment]
rufus-scheduler 3.5.1 and fugit 1.1.4 released. Thanks!
