### ISSUE TITLE
Incorrect schedule in certain timezone when using hash cron extention

### ISSUE THREAD

**Issue by phibid** [floraison/fugit#67]
Opening an issue here too after opening it in Gitlab, https://gitlab.com/gitlab-org/gitlab/-/issues/354513, as it seems that Fugit is being used in Gitlab for the cron process.

The use of the cron hash extension don't give the correct schedule in some timezone.
For example, in UTC, 30 18 * * 2#5 will correctly be scheduled the last Tuesday of this month, the 29th.
However, in Paris timezone, it will be scheduled in 2 months, the last Tuesday of May, the 24th.

Not sure if this issue is coming from Fugit or from the implementation done by Gitlab, but if you think that you are not concerned by this bug, just feel free to close this issue.

**Comment by jmettraux** [comment]
Hello @phibid, what version of fugit is used by Gitlab?

Thanks in advance.

**Comment by jmettraux** [comment]
@phibid thanks for reporting that.

I'm seeing the issue with fugit 1.2.1 and the current 1.5.3 pre.

Although it points at the fifth Tuesday of May for me, 2022-05-31 but not the 2022-05-24 you seem to be seeing.

I will attempt to fix that. Give me a few days.

**Comment by phibid** [comment]
Ah yes sorry, typo, last Tuesday of May being the "May 31, 2022 6:30pm GMT+0200", not the 24th

Thanks !

**Comment by jmettraux** [comment]
@phibid Please upgrade your et-orbi gem to 1.2.7 and try again. Tell me if it fixes the issue for you.

**Comment by jmettraux** [comment]
@phibid OK, I saw your added info on Gitlab, I will complement it there.

Closing the issue here. I am ready to re-open it if necessary.

Thanks again!
