### ISSUE TITLE
Fugit.parse_cronish(str) and .do_parse_cronish(str)

### ISSUE THREAD

**Issue by jmettraux** [floraison/fugit#70]
A combo of `Fugit.parse_cron` and `Fugit.parse_nat` that returns a `Fugit;:Cron` instance (or nil).

To cover the case at https://github.com/ondrejbartas/sidekiq-cron/pull/312

**Comment by markets** [comment]
Hello @jmettraux 👋🏼 

I'm one of the maintainers of `sidekiq-cron`. Just sending a friendly ping 🙏🏼 this provides a much better API for parsing user generated content 👌🏼

**Comment by jmettraux** [comment]
Hey @markets, thanks for the ping!

Give me one or two days. And thanks for your hard work on `sidekiq-cron`.

**Comment by markets** [comment]
hi @jmettraux, just opened a pull request using this new API: https://github.com/sidekiq-cron/sidekiq-cron/pull/385

It seems to work fine!

**Comment by jmettraux** [comment]
Fugit 1.8.0 has been [released](https://rubygems.org/gems/fugit/versions/1.8.0).

Thanks again for the ping! Please tell me if you need anything else. Kind regards.
