### ISSUE TITLE
strip before parsing?

### ISSUE THREAD

**Issue by jjb** [floraison/fugit#74]
## Issue description

it looks like a leading space makes the parser crash. works: `"45 5 * * sun"` breaks: `" 45 5 * * sun"`. could fugit be changed to simply strip the string before parsing?

## How to reproduce

```ruby
c = Fugit.parse(" 45 5 * * sun")
```

## Error and error backtrace (if any)

```
Message: invalid cron string " 45 5 * * sun"
```

## Expected behaviour

cron string to parse without error

## Context

ruby-clock (0.8.0.rc3)
rufus-scheduler (3.8.0)
fugit (1.5.2)
et-orbi (1.2.5)
raabro (1.4.0)

**Comment by jmettraux** [comment]
> Could fugit be changed to simply strip the string before parsing?

OK, I will do it then.

**Comment by jmettraux** [comment]
Hello @jjb please tell me if those changes are OK and/or if you have further suggestions/feedback. Once it's all good, I'll release fugit 1.6.0.

Thanks for reporting this inconsistency!

**Comment by jjb** [comment]
Wow, nice! Sorry for not responding earlier, I need to adjust my github notifications apparently.

Thanks!

**Comment by jmettraux** [comment]
You're welcome!
